### ISSUE TITLE
About publication of your work

### ISSUE THREAD

**Issue by sunset222** [uci-cbcl/esm-efficient#1]
Hi, 

Thank you for your great job in AI/Proteomics field :D.
I am interested to your work and trying to apply to finetune the model with my own data. 

Is your work in the middle of the peer reviewing process? or will it be publish soon?
just wanna know when I can cite your official paper in our work.

Thank you again

**Comment by MuhammedHasan** [comment]
Our manuscript added to readme: https://www.biorxiv.org/content/10.1101/2024.10.22.619563v1
