### ISSUE TITLE
Could you please provide a complete environment configuration file `environment.yml`.

### ISSUE THREAD

**Issue by JiaLonghao1997** [uci-cbcl/esm-efficient#8]
What version of Python are you using?
 
The latest version of cudatoolkit on conda is 11.8, but you installed version 12.5 of cudatoolkit. 

The latest version of cuda-toolkit is 12.6. Should I install cuda-toolkit or cudatoolkit?
- cuda-toolkit:  https://anaconda.org/nvidia/cuda-toolkit
- cudatoolkit:  https://anaconda.org/conda-forge/cudatoolkit

**Comment by MuhammedHasan** [comment]
You can use the latest version. See the https://pytorch.org/get-started/locally/ page. You do not have to use a specific Cuda toolkit.
